# Generated by Django 4.2.16 on 2026-05-15 13:44

import apps.reservations.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона.', regex='^\\+?[0-9\\s\\-()]{7,20}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date', models.DateField(validators=[apps.reservations.validators.validate_not_past_date], verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('guests_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Количество гостей')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='contacts.branch', verbose_name='Филиал')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='contacts.hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['branch', 'date', 'status'], name='reservation_branch__1ceefc_idx')],
            },
        ),
    ]
