# Generated by Django 4.2.16 on 2026-05-15 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Текст')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено (SMS отключены)')], max_length=10, verbose_name='Статус')),
                ('provider_response', models.TextField(blank=True, verbose_name='Ответ провайдера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='reservations.reservation', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'SMS-лог',
                'verbose_name_plural': 'SMS-логи',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='reservation_status_5e543d_idx')],
            },
        ),
    ]
