-- ============================================================================
--  schema.sql — полная DDL-схема БД ресторана Sandyq (PostgreSQL)
--  Сгенерировано из применённых миграций Django (sqlmigrate).
--  Дата: 2026-05-15
--  Прикладные таблицы: contacts_city/branch/hall, menu_category/menuitem,
--  reservations_reservation/smslog, gallery_galleryphoto (+ системные Django).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- contenttypes / 0001_initial
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Create model ContentType
--
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
--
-- Alter unique_together for contenttype (1 constraint(s))
--
ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");
COMMIT;

-- ----------------------------------------------------------------------------
-- auth / 0001_initial
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Create model Permission
--
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL);
--
-- Create model Group
--
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model User
--
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NOT NULL, "is_superuser" boolean NOT NULL, "username" varchar(30) NOT NULL UNIQUE, "first_name" varchar(30) NOT NULL, "last_name" varchar(30) NOT NULL, "email" varchar(75) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL);
CREATE TABLE "auth_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "auth_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "permission_id" integer NOT NULL);
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops);
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE INDEX "auth_user_username_6821ab7c_like" ON "auth_user" ("username" varchar_pattern_ops);
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
COMMIT;

-- ----------------------------------------------------------------------------
-- admin / 0001_initial
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Create model LogEntry
--
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL, "user_id" integer NOT NULL);
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
COMMIT;

-- ----------------------------------------------------------------------------
-- admin / 0002_logentry_remove_auto_add
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Alter field action_time on logentry
--
-- (no-op)
COMMIT;

-- ----------------------------------------------------------------------------
-- admin / 0003_logentry_add_action_flag_choices
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Alter field action_flag on logentry
--
-- (no-op)
COMMIT;

-- ----------------------------------------------------------------------------
-- contenttypes / 0002_remove_content_type_name
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Change Meta options on contenttype
--
-- (no-op)
--
-- Alter field name on contenttype
--
ALTER TABLE "django_content_type" ALTER COLUMN "name" DROP NOT NULL;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Remove field name from contenttype
--
ALTER TABLE "django_content_type" DROP COLUMN "name" CASCADE;
COMMIT;

-- ----------------------------------------------------------------------------
-- auth / 0002_alter_permission_name_max_length
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Alter field name on permission
--
ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255);
COMMIT;

-- ----------------------------------------------------------------------------
-- auth / 0003_alter_user_email_max_length
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Alter field email on user
--
ALTER TABLE "auth_user" ALTER COLUMN "email" TYPE varchar(254);
COMMIT;

-- ----------------------------------------------------------------------------
-- auth / 0004_alter_user_username_opts
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- ----------------------------------------------------------------------------
-- auth / 0005_alter_user_last_login_null
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Alter field last_login on user
--
ALTER TABLE "auth_user" ALTER COLUMN "last_login" DROP NOT NULL;
COMMIT;

-- ----------------------------------------------------------------------------
-- auth / 0006_require_contenttypes_0002
-- ----------------------------------------------------------------------------


-- ----------------------------------------------------------------------------
-- auth / 0007_alter_validators_add_error_messages
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- ----------------------------------------------------------------------------
-- auth / 0008_alter_user_username_max_length
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Alter field username on user
--
ALTER TABLE "auth_user" ALTER COLUMN "username" TYPE varchar(150);
COMMIT;

-- ----------------------------------------------------------------------------
-- auth / 0009_alter_user_last_name_max_length
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Alter field last_name on user
--
ALTER TABLE "auth_user" ALTER COLUMN "last_name" TYPE varchar(150);
COMMIT;

-- ----------------------------------------------------------------------------
-- auth / 0010_alter_group_name_max_length
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Alter field name on group
--
ALTER TABLE "auth_group" ALTER COLUMN "name" TYPE varchar(150);
COMMIT;

-- ----------------------------------------------------------------------------
-- auth / 0011_update_proxy_permissions
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- ----------------------------------------------------------------------------
-- auth / 0012_alter_user_first_name_max_length
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Alter field first_name on user
--
ALTER TABLE "auth_user" ALTER COLUMN "first_name" TYPE varchar(150);
COMMIT;

-- ----------------------------------------------------------------------------
-- contacts / 0001_initial
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Create model Branch
--
CREATE TABLE "contacts_branch" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "address" varchar(255) NOT NULL, "phone" varchar(20) NOT NULL, "email" varchar(254) NOT NULL, "working_hours" varchar(120) NOT NULL, "google_maps_link" varchar(200) NOT NULL, "is_active" boolean NOT NULL);
--
-- Create model City
--
CREATE TABLE "contacts_city" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL UNIQUE, "slug" varchar(120) NOT NULL UNIQUE);
--
-- Create model Hall
--
CREATE TABLE "contacts_hall" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(120) NOT NULL, "capacity" integer NOT NULL CHECK ("capacity" >= 0), "description" text NOT NULL, "image" varchar(100) NULL, "branch_id" bigint NOT NULL);
--
-- Add field city to branch
--
ALTER TABLE "contacts_branch" ADD COLUMN "city_id" bigint NOT NULL CONSTRAINT "contacts_branch_city_id_9bbd1617_fk_contacts_city_id" REFERENCES "contacts_city"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "contacts_branch_city_id_9bbd1617_fk_contacts_city_id" IMMEDIATE;
--
-- Create constraint unique_hall_name_per_branch on model hall
--
ALTER TABLE "contacts_hall" ADD CONSTRAINT "unique_hall_name_per_branch" UNIQUE ("branch_id", "name");
--
-- Create constraint unique_branch_address_per_city on model branch
--
ALTER TABLE "contacts_branch" ADD CONSTRAINT "unique_branch_address_per_city" UNIQUE ("city_id", "address");
CREATE INDEX "contacts_city_name_a9314230_like" ON "contacts_city" ("name" varchar_pattern_ops);
CREATE INDEX "contacts_city_slug_9cd6bc9b_like" ON "contacts_city" ("slug" varchar_pattern_ops);
ALTER TABLE "contacts_hall" ADD CONSTRAINT "contacts_hall_branch_id_ee7d56d6_fk_contacts_branch_id" FOREIGN KEY ("branch_id") REFERENCES "contacts_branch" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "contacts_hall_branch_id_ee7d56d6" ON "contacts_hall" ("branch_id");
CREATE INDEX "contacts_branch_city_id_9bbd1617" ON "contacts_branch" ("city_id");
COMMIT;

-- ----------------------------------------------------------------------------
-- gallery / 0001_initial
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Create model GalleryPhoto
--
CREATE TABLE "gallery_galleryphoto" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "image" varchar(100) NOT NULL, "caption" varchar(200) NOT NULL, "order" integer NOT NULL CHECK ("order" >= 0), "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL);
CREATE INDEX "gallery_gal_is_acti_96e6fe_idx" ON "gallery_galleryphoto" ("is_active", "order");
COMMIT;

-- ----------------------------------------------------------------------------
-- gallery / 0002_alter_galleryphoto_options
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Change Meta options on galleryphoto
--
-- (no-op)
COMMIT;

-- ----------------------------------------------------------------------------
-- menu / 0001_initial
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Create model Category
--
CREATE TABLE "menu_category" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(120) NOT NULL UNIQUE, "slug" varchar(140) NOT NULL UNIQUE, "order" integer NOT NULL CHECK ("order" >= 0), "image" varchar(100) NULL);
--
-- Create model MenuItem
--
CREATE TABLE "menu_menuitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(160) NOT NULL, "description" text NOT NULL, "price" numeric(10, 2) NOT NULL, "weight" integer NULL CHECK ("weight" >= 0), "image" varchar(100) NULL, "is_available" boolean NOT NULL, "is_featured" boolean NOT NULL, "category_id" bigint NOT NULL);
--
-- Create constraint unique_item_per_category on model menuitem
--
ALTER TABLE "menu_menuitem" ADD CONSTRAINT "unique_item_per_category" UNIQUE ("category_id", "name");
CREATE INDEX "menu_category_name_3df82881_like" ON "menu_category" ("name" varchar_pattern_ops);
CREATE INDEX "menu_category_slug_9da38891_like" ON "menu_category" ("slug" varchar_pattern_ops);
ALTER TABLE "menu_menuitem" ADD CONSTRAINT "menu_menuitem_category_id_af353a3b_fk_menu_category_id" FOREIGN KEY ("category_id") REFERENCES "menu_category" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "menu_menuitem_category_id_af353a3b" ON "menu_menuitem" ("category_id");
CREATE INDEX "menu_menuit_is_avai_74a54e_idx" ON "menu_menuitem" ("is_available", "is_featured");
COMMIT;

-- ----------------------------------------------------------------------------
-- reservations / 0001_initial
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Create model Reservation
--
CREATE TABLE "reservations_reservation" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "first_name" varchar(80) NOT NULL, "last_name" varchar(80) NOT NULL, "phone" varchar(20) NOT NULL, "email" varchar(254) NOT NULL, "date" date NOT NULL, "time" time NOT NULL, "guests_count" smallint NOT NULL CHECK ("guests_count" >= 0), "comment" text NOT NULL, "status" varchar(10) NOT NULL, "created_at" timestamp with time zone NOT NULL, "branch_id" bigint NOT NULL, "hall_id" bigint NOT NULL);
ALTER TABLE "reservations_reservation" ADD CONSTRAINT "reservations_reserva_branch_id_6e0bb7fd_fk_contacts_" FOREIGN KEY ("branch_id") REFERENCES "contacts_branch" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "reservations_reservation" ADD CONSTRAINT "reservations_reservation_hall_id_6994444d_fk_contacts_hall_id" FOREIGN KEY ("hall_id") REFERENCES "contacts_hall" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "reservations_reservation_branch_id_6e0bb7fd" ON "reservations_reservation" ("branch_id");
CREATE INDEX "reservations_reservation_hall_id_6994444d" ON "reservations_reservation" ("hall_id");
CREATE INDEX "reservation_branch__1ceefc_idx" ON "reservations_reservation" ("branch_id", "date", "status");
COMMIT;

-- ----------------------------------------------------------------------------
-- reservations / 0002_smslog
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Create model SMSLog
--
CREATE TABLE "reservations_smslog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "phone" varchar(20) NOT NULL, "message" text NOT NULL, "status" varchar(10) NOT NULL, "provider_response" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "reservation_id" bigint NULL);
ALTER TABLE "reservations_smslog" ADD CONSTRAINT "reservations_smslog_reservation_id_1f696248_fk_reservati" FOREIGN KEY ("reservation_id") REFERENCES "reservations_reservation" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "reservations_smslog_reservation_id_1f696248" ON "reservations_smslog" ("reservation_id");
CREATE INDEX "reservation_status_5e543d_idx" ON "reservations_smslog" ("status", "created_at");
COMMIT;

-- ----------------------------------------------------------------------------
-- sessions / 0001_initial
-- ----------------------------------------------------------------------------
BEGIN;
--
-- Create model Session
--
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL);
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
COMMIT;

