# Generated by Django 4.2.16 on 2026-05-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Фотогалерея',
                'ordering': ('order', '-created_at'),
                'indexes': [models.Index(fields=['is_active', 'order'], name='gallery_gal_is_acti_96e6fe_idx')],
            },
        ),
    ]
