# Generated by Django 4.2.16 on 2026-05-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'ordering': ('order',), 'verbose_name': 'Фото галереи', 'verbose_name_plural': 'Фотогалерея'},
        ),
    ]
